update
SukkaW/OpenCore-Document-zh_Hans pull request #48
Opened 2022-07-17 02:49 UTC by cike-567

<merge>(<update>): <from {base branch name} into {target branch name}>
<BLANK LINE(Not necessary)>
<body>

2022-07-18 11:27 UTC, SukkaW requested changes

2022-07-18 11:27 UTC, SukkaW commented on source/4-acpi.md
> +author_info: 由 Sukka cike-567整理、由 Sukka、derbalkon、EricKwok cike-567翻译。感谢黑果小兵提供的参考资料
```suggestion
author_info: 由 Sukka、cike-567 整理、由 Sukka、derbalkon、EricKwok、cike-567 翻译。感谢黑果小兵提供的参考资料
```

2022-07-18 11:34 UTC, SukkaW requested changes

2022-07-18 11:34 UTC, SukkaW commented on source/10-platform-info.md
> +**Description**: 平台功能位掩码（在较旧的Mac上缺失），详情请参考 [AppleFeatures.h](https://github.com/acidanthera/OpenCorePkg/blob/master/Include/Apple/IndustryStandard/AppleFeatures.h)。
```suggestion
**Description**: 平台功能位掩码（较旧的 Mac 上缺失该位掩码），详情请参考 [AppleFeatures.h](https://github.com/acidanthera/OpenCorePkg/blob/master/Include/Apple/IndustryStandard/AppleFeatures.h)。
```

2022-07-18 11:34 UTC, SukkaW commented on source/4-acpi.md
> +author_info: 由 Sukka、cike-567整理、由 Sukka、derbalkon、EricKwok、cike-567翻译。感谢黑果小兵提供的参考资料
```suggestion
author_info: 由 Sukka、cike-567 整理、由 Sukka、derbalkon、EricKwok、cike-567 翻译。感谢黑果小兵提供的参考资料
```

2022-07-19 01:18 UTC, cike-567 commented
你可以说中文的

2022-07-20 03:50 UTC, closed without merging